# Generated by scripts/generate_sync_sdk.py. Do not edit.
from __future__ import annotations

from functools import partial
from typing import Callable

import httpx
from anyio.from_thread import start_blocking_portal
from pydantic import JsonValue

from .assurance_models import AssuranceSession, DurableJob
from .compilation_models import CompilationResult
from .connection_api import ConnectionList, ConnectionView
from .domain import CapabilityResponse
from .sdk_async import AsyncDoneProof
from .sdk_common import Cancellation, ConnectionOnboarding, ProviderCatalog, RequestLog


class _Resource:
    def __init__(self, resource, invoke):
        self._async, self._invoke = resource, invoke


class DoneProof:
    """Synchronous facade using one owned event loop and the async policy implementation.

    Close the client or use a context manager to release its worker thread.
    Custom transports use httpx.AsyncBaseTransport in both client variants.
    """
    def __init__(self, *, api_key: str, base_url: str = 'https://www.getdoneproof.com',
                 timeout: float = 30, transport: httpx.AsyncBaseTransport | None = None,
                 log_hook: Callable[[RequestLog], None] | None = None):
        self._async = AsyncDoneProof(api_key=api_key, base_url=base_url, timeout=timeout,
                                    transport=transport, log_hook=log_hook)
        self._context = start_blocking_portal()
        self._portal = self._context.__enter__()
        self._closed = False
        self.assurance = Assurance(self._async.assurance, self._invoke)
        self.providers = Providers(self._async.providers, self._invoke)

    def _invoke(self, function, *args, **kwargs):
        return self._portal.call(partial(function, *args, **kwargs))

    def close(self):
        if not self._closed:
            try:
                self._invoke(self._async.close)
            finally:
                self._closed = True
                self._context.__exit__(None, None, None)

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()

    verify_receipt = staticmethod(AsyncDoneProof.verify_receipt)

    def capabilities(self) -> CapabilityResponse:
        return self._invoke(self._async.capabilities)

    def get_job(self, job_id: str) -> DurableJob:
        return self._invoke(self._async.get_job, job_id)

    def cancel_job(self, job_id: str) -> DurableJob:
        return self._invoke(self._async.cancel_job, job_id)

    def wait_for_verification(self, job_id: str, *, timeout: float=120, cancellation: Cancellation | None=None) -> DurableJob:
        return self._invoke(self._async.wait_for_verification, job_id, timeout=timeout, cancellation=cancellation)

    def list_connections(self) -> ConnectionList:
        return self._invoke(self._async.list_connections)

    def connection_status(self, connection_id: str) -> ConnectionView:
        return self._invoke(self._async.connection_status, connection_id)

    def begin_connection(self, provider: str) -> ConnectionOnboarding:
        return self._invoke(self._async.begin_connection, provider)

    def disconnect(self, connection_id: str, *, expected_revision: int, idempotency_key: str) -> ConnectionView:
        return self._invoke(self._async.disconnect, connection_id, expected_revision=expected_revision, idempotency_key=idempotency_key)


class Assurance(_Resource):

    def prepare(self, *, task: str, idempotency_key: str, context: dict[str, JsonValue] | None=None, timeout: float=150, cancellation: Cancellation | None=None) -> AssuranceSession:
        return self._invoke(self._async.prepare, task=task, idempotency_key=idempotency_key, context=context, timeout=timeout, cancellation=cancellation)

    def get(self, session_id: str) -> AssuranceSession:
        return self._invoke(self._async.get, session_id)

    def verify(self, session_id: str, *, wait: bool=False, timeout: float=120, deadline_seconds: int=300, callback_id: str | None=None, cancellation: Cancellation | None=None) -> AssuranceSession:
        return self._invoke(self._async.verify, session_id, wait=wait, timeout=timeout, deadline_seconds=deadline_seconds, callback_id=callback_id, cancellation=cancellation)

    def reverify(self, session_id: str, *, previous_receipt_id: str, idempotency_key: str, wait: bool=False, timeout: float=120, deadline_seconds: int=300, callback_id: str | None=None, cancellation: Cancellation | None=None) -> AssuranceSession:
        return self._invoke(self._async.reverify, session_id, previous_receipt_id=previous_receipt_id, idempotency_key=idempotency_key, wait=wait, timeout=timeout, deadline_seconds=deadline_seconds, callback_id=callback_id, cancellation=cancellation)

    def wait_for_verification(self, session_id: str, *, timeout: float=120, cancellation: Cancellation | None=None) -> AssuranceSession:
        return self._invoke(self._async.wait_for_verification, session_id, timeout=timeout, cancellation=cancellation)


class Providers(_Resource):

    def available(self) -> CapabilityResponse:
        return self._invoke(self._async.available)

    def declarations(self, *, refresh: bool=False) -> ProviderCatalog:
        return self._invoke(self._async.declarations, refresh=refresh)

    def for_task(self, *, task: str, context: dict[str, JsonValue] | None=None) -> CompilationResult:
        return self._invoke(self._async.for_task, task=task, context=context)
