from __future__ import annotations

import html

from .domain import VerificationReceipt


LANDING_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DoneProof — Outcome assurance for AI agents</title>
<style>
:root{--bg:#081018;--panel:#0d1823;--line:#203244;--text:#f3f7fb;--muted:#9bb0c3;--accent:#73d2ff;--green:#50d890}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% 0,#102b3b 0,transparent 38%),var(--bg);color:var(--text);font:16px/1.55 Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}.wrap{max-width:1120px;margin:auto;padding:0 28px}.nav{display:flex;align-items:center;justify-content:space-between;padding:28px 0}.brand{font-weight:800;letter-spacing:-.02em;font-size:20px}.pill{border:1px solid var(--line);border-radius:999px;padding:8px 13px;color:var(--muted);font-size:13px}.hero{padding:100px 0 80px;max-width:900px}.hero h1{font-size:clamp(52px,8vw,88px);line-height:.98;letter-spacing:-.055em;margin:0 0 28px}.hero p{font-size:21px;color:var(--muted);max-width:760px}.actions{display:flex;gap:12px;margin-top:34px;flex-wrap:wrap}.btn{padding:13px 18px;border-radius:10px;text-decoration:none;font-weight:700}.primary{background:var(--text);color:#081018}.secondary{border:1px solid var(--line);color:var(--text)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:20px 0 90px}.card{background:linear-gradient(180deg,#0f1b27,#0b151f);border:1px solid var(--line);border-radius:16px;padding:24px}.card h3{margin:0 0 9px;font-size:17px}.card p{color:var(--muted);margin:0}.flow{border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:50px 0;margin-bottom:60px;color:var(--muted);font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.flow b{color:var(--green)}footer{padding:0 0 50px;color:var(--muted);font-size:13px}@media(max-width:800px){.grid{grid-template-columns:1fr}.hero{padding-top:60px}}
</style></head><body><div class="wrap"><nav class="nav"><div class="brand">DoneProof</div><div class="pill">Outcome assurance infrastructure</div></nav>
<section class="hero"><h1>Agents act.<br>DoneProof verifies.</h1><p>Independent, machine-verifiable evidence that an AI agent actually produced the requested external outcome—not merely that a tool call returned success.</p><div class="actions"><a class="btn primary" href="/console">Open assurance console</a><a class="btn secondary" href="/docs">API reference</a></div></section>
<div class="flow">intent → completion contract → independent observation → deterministic predicates → <b>signed receipt</b></div>
<section class="grid"><div class="card"><h3>Independent verification</h3><p>GitHub, Gmail and trusted enterprise webhook evidence are checked outside the execution agent's own claims.</p></div><div class="card"><h3>Tamper-evident receipts</h3><p>Every verification result is hashed and signed with Ed25519 for portable audit evidence.</p></div><div class="card"><h3>Safe uncertainty</h3><p>Ambiguous, inaccessible or incomplete evidence returns UNKNOWN. DoneProof never guesses its way to success.</p></div></section>
<footer>DoneProof pilot · API-first outcome assurance for autonomous work</footer></div></body></html>"""


CONSOLE_HTML = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DoneProof Assurance Console</title>
<style>
:root{--bg:#071019;--panel:#0e1924;--panel2:#111f2c;--line:#223649;--text:#eff6fb;--muted:#91a8bc;--green:#4fd58b;--amber:#f0b65b;--red:#ff7b7b;--blue:#73cfff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,system-ui,sans-serif}.shell{display:grid;grid-template-columns:230px 1fr;min-height:100vh}.side{border-right:1px solid var(--line);padding:26px 20px;background:#09131d}.logo{font-size:19px;font-weight:800;margin-bottom:42px}.navitem{padding:10px 12px;border-radius:8px;margin:4px 0;color:var(--muted)}.navitem.active{background:var(--panel2);color:var(--text)}.main{padding:34px;max-width:1300px;width:100%}.top{display:flex;justify-content:space-between;align-items:center;gap:16px}.top h1{font-size:28px;margin:0}.sub{color:var(--muted);margin-top:5px}.key{background:var(--panel);border:1px solid var(--line);color:var(--text);border-radius:8px;padding:9px 11px;width:260px}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:28px 0}.card,.tablewrap{background:var(--panel);border:1px solid var(--line);border-radius:13px}.card{padding:17px}.label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.06em}.value{font-size:28px;font-weight:760;margin-top:7px}.tablewrap{overflow:hidden}.tablehead{padding:18px 20px;border-bottom:1px solid var(--line);font-weight:700}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px 20px;border-bottom:1px solid #172838}th{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}td.task{max-width:520px}.badge{padding:5px 9px;border-radius:999px;font-weight:700;font-size:11px;display:inline-block}.VERIFIED{color:var(--green);background:#123226}.PARTIAL{color:var(--amber);background:#332914}.FAILED{color:var(--red);background:#351b1e}.UNKNOWN{color:var(--blue);background:#152b38}.empty{padding:50px;text-align:center;color:var(--muted)}.providers{color:var(--muted);font-size:12px}.rid{font-family:ui-monospace,monospace;font-size:12px;color:var(--muted)}@media(max-width:900px){.shell{grid-template-columns:1fr}.side{display:none}.cards{grid-template-columns:repeat(2,1fr)}.main{padding:20px}.key{width:190px}}@media(max-width:600px){.cards{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.key{width:100%}th:nth-child(4),td:nth-child(4){display:none}}
</style></head><body><div class="shell"><aside class="side"><div class="logo">DoneProof</div><div class="navitem active">Assurance</div><a class="navitem" style="display:block;text-decoration:none" href="/docs">API reference</a><a class="navitem" style="display:block;text-decoration:none" href="/v1/capabilities">Capabilities</a></aside><main class="main"><div class="top"><div><h1>Outcome assurance</h1><div class="sub">Independent evidence from agent actions</div></div><input id="key" class="key" type="password" placeholder="Workspace API key (if enabled)"></div>
<div class="cards"><div class="card"><div class="label">Total</div><div id="total" class="value">—</div></div><div class="card"><div class="label">Verified</div><div id="verified" class="value">—</div></div><div class="card"><div class="label">Partial</div><div id="partial" class="value">—</div></div><div class="card"><div class="label">Failed</div><div id="failed" class="value">—</div></div><div class="card"><div class="label">Unknown</div><div id="unknown" class="value">—</div></div></div>
<div class="tablewrap"><div class="tablehead">Recent verifications</div><div id="content"><div class="empty">Loading assurance data…</div></div></div></main></div>
<script>
const key=document.getElementById('key');key.value=localStorage.getItem('doneproof_key')||'';key.addEventListener('change',()=>{localStorage.setItem('doneproof_key',key.value);load()});
function headers(){return key.value?{'X-DoneProof-Key':key.value}:{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function load(){try{const [s,r]=await Promise.all([fetch('/v1/overview',{headers:headers()}),fetch('/v1/receipts?limit=30',{headers:headers()})]);if(!s.ok||!r.ok)throw new Error(s.status===401?'Enter a valid workspace API key':'Assurance API unavailable');const stats=await s.json(),receipts=await r.json();for(const k of ['total','verified','partial','failed','unknown'])document.getElementById(k).textContent=stats[k.toUpperCase()]??stats[k]??0;const c=document.getElementById('content');if(!receipts.length){c.innerHTML='<div class="empty">No verification receipts yet.</div>';return}c.innerHTML='<table><thead><tr><th>Outcome</th><th>Task</th><th>Evidence</th><th>Assurance</th><th>Receipt</th><th>Time</th></tr></thead><tbody>'+receipts.map(x=>`<tr><td><span class="badge ${x.verdict}">${x.verdict}</span></td><td class="task">${esc(x.task)}</td><td><div>${x.summary.passed}/${x.summary.total} conditions</div><div class="providers">${esc(x.summary.providers.join(' · '))}</div></td><td>${esc(x.assurance_level)}</td><td class="rid">${esc(x.receipt_id)}</td><td>${new Date(x.verified_at).toLocaleString()}</td></tr>`).join('')+'</tbody></table>'}catch(e){document.getElementById('content').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
load();
</script></body></html>"""


def certificate_html(receipt: VerificationReceipt) -> str:
    items = "".join(
        f"<tr><td>{html.escape(r.description)}</td><td><b>{html.escape(r.status.value)}</b></td><td>{html.escape(r.evidence.provider)}</td></tr>"
        for r in receipt.results if r.required
    )
    return f"""<!doctype html><html><head><meta charset='utf-8'><title>DoneProof receipt {html.escape(receipt.receipt_id)}</title><style>body{{font:15px/1.55 system-ui;max-width:850px;margin:60px auto;padding:0 24px;color:#16202a}}h1{{font-size:34px}}.v{{font-size:24px;font-weight:800}}table{{width:100%;border-collapse:collapse;margin:28px 0}}td,th{{padding:10px;border-bottom:1px solid #dfe6eb;text-align:left}}code{{word-break:break-all;color:#53626f}}.muted{{color:#687887}}</style></head><body><div class='muted'>DONEPROOF VERIFICATION RECEIPT</div><h1>{html.escape(receipt.task)}</h1><div class='v'>{html.escape(receipt.verdict.value)}</div><p><b>Assurance:</b> {html.escape(receipt.assurance_level)} · {receipt.summary.passed} of {receipt.summary.total} evaluated conditions passed. Verified {html.escape(receipt.verified_at.isoformat())}.</p><table><thead><tr><th>Required outcome</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{items}</tbody></table><p class='muted'>Receipt ID</p><code>{html.escape(receipt.receipt_id)}</code><p class='muted'>SHA-256 receipt hash</p><code>{html.escape(receipt.receipt_hash)}</code><p class='muted'>Signing key</p><code>{html.escape(receipt.key_id)} · Ed25519</code><p class='muted'>This certificate summarizes the signed machine-readable receipt. Cryptographic verification should use the JSON receipt and DoneProof signing key.</p></body></html>"""
