from __future__ import annotations

import html

from .domain import VerificationReceipt

LANDING_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DoneProof — Independent outcome assurance for AI agents</title>
<style>
:root{--bg:#071019;--panel:#0d1823;--line:#203244;--text:#f3f7fb;--muted:#9bb0c3;--green:#50d890;--blue:#73d2ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 72% 0,#103046 0,transparent 36%),var(--bg);color:var(--text);font:16px/1.58 Inter,ui-sans-serif,system-ui,-apple-system,sans-serif}.wrap{max-width:1140px;margin:auto;padding:0 28px}.nav{display:flex;align-items:center;justify-content:space-between;padding:28px 0}.brand{font-weight:850;letter-spacing:-.03em;font-size:21px}.pill{border:1px solid var(--line);border-radius:999px;padding:8px 13px;color:var(--muted);font-size:13px}.hero{padding:92px 0 72px;max-width:940px}.eyebrow{color:var(--blue);font-size:13px;font-weight:750;letter-spacing:.09em;text-transform:uppercase;margin-bottom:18px}.hero h1{font-size:clamp(50px,7.5vw,84px);line-height:.99;letter-spacing:-.055em;margin:0 0 27px}.hero p{font-size:21px;color:var(--muted);max-width:790px}.actions{display:flex;gap:12px;margin-top:32px;flex-wrap:wrap}.btn{padding:13px 18px;border-radius:10px;text-decoration:none;font-weight:750}.primary{background:var(--text);color:#071019}.secondary{border:1px solid var(--line);color:var(--text)}.flow{border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:36px 0;margin:10px 0 62px;color:var(--muted);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:14px}.flow b{color:var(--green)}.sectiontitle{font-size:32px;letter-spacing:-.035em;margin:0 0 10px}.lead{color:var(--muted);max-width:760px;margin:0 0 28px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:0 0 72px}.card{background:linear-gradient(180deg,#0f1b27,#0b151f);border:1px solid var(--line);border-radius:16px;padding:24px}.card h3{margin:0 0 9px;font-size:17px}.card p{color:var(--muted);margin:0}.compare{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:76px}.compare .card{padding:28px}.good{color:var(--green)}.muted{color:var(--muted)}footer{border-top:1px solid var(--line);padding:32px 0 48px;color:var(--muted);font-size:13px}@media(max-width:800px){.grid,.compare{grid-template-columns:1fr}.hero{padding-top:55px}.hero h1{font-size:52px}}
</style></head><body><div class="wrap"><nav class="nav"><div class="brand">DoneProof</div><div class="pill">Independent outcome assurance</div></nav>
<section class="hero"><div class="eyebrow">For autonomous work that must actually be complete</div><h1>Agents act.<br>DoneProof verifies.</h1><p>DoneProof independently checks the destination system and produces signed evidence that the requested business outcome is true. It works across model vendors, agent frameworks and internal automation.</p><div class="actions"><a class="btn primary" href="/demo">Watch 90-second demo</a><a class="btn secondary" href="/console">Open assurance console</a><a class="btn secondary" href="/docs">API reference</a></div></section>
<div class="flow">desired outcome → register assurance boundary → agent executes → independent external evidence → deterministic checks → <b>signed verdict</b></div>
<h2 class="sectiontitle">A separate trust layer for agent outcomes</h2><p class="lead">Tool-call success and agent traces describe execution. DoneProof verifies the external state the business actually cares about.</p>
<section class="grid"><div class="card"><h3>Independent evidence</h3><p>Read GitHub, Gmail or trusted customer-system evidence outside the executor's own success claim.</p></div><div class="card"><h3>Deterministic acceptance</h3><p>Explicit postconditions decide whether an outcome passes. Ambiguous evidence becomes UNKNOWN rather than invented certainty.</p></div><div class="card"><h3>Portable proof</h3><p>Every receipt binds to the exact completion contract and is signed with Ed25519 for audit and incident review.</p></div></section>
<section class="compare"><div class="card"><h3>Observability tells you</h3><p class="muted">what the agent attempted, which tools it called, how it reasoned and where execution failed.</p></div><div class="card"><h3 class="good">DoneProof tells you</h3><p class="muted">whether the required external outcome is independently supported by authoritative evidence.</p></div></section>
<footer>DoneProof · Outcome assurance infrastructure for AI agents</footer></div></body></html>"""


CONSOLE_HTML = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DoneProof Assurance Console</title>
<style>
:root{--bg:#071019;--panel:#0e1924;--panel2:#111f2c;--line:#223649;--text:#eff6fb;--muted:#91a8bc;--green:#4fd58b;--amber:#f0b65b;--red:#ff7b7b;--blue:#73cfff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,system-ui,sans-serif}.shell{display:grid;grid-template-columns:230px 1fr;min-height:100vh}.side{border-right:1px solid var(--line);padding:26px 20px;background:#09131d}.logo{font-size:19px;font-weight:800;margin-bottom:42px}.navitem{padding:10px 12px;border-radius:8px;margin:4px 0;color:var(--muted)}.navitem.active{background:var(--panel2);color:var(--text)}.main{padding:34px;max-width:1320px;width:100%}.top{display:flex;justify-content:space-between;align-items:center;gap:16px}.top h1{font-size:28px;margin:0}.sub{color:var(--muted);margin-top:5px}.key{background:var(--panel);border:1px solid var(--line);color:var(--text);border-radius:8px;padding:9px 11px;width:270px}.hint{color:var(--muted);font-size:11px;margin-top:6px;text-align:right}.cards{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:28px 0}.card,.tablewrap{background:var(--panel);border:1px solid var(--line);border-radius:13px}.card{padding:17px}.label{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.06em}.value{font-size:27px;font-weight:760;margin-top:7px}.tablewrap{overflow:hidden}.tablehead{padding:18px 20px;border-bottom:1px solid var(--line);font-weight:700}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px 20px;border-bottom:1px solid #172838}th{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}td.task{max-width:500px}.badge{padding:5px 9px;border-radius:999px;font-weight:700;font-size:11px;display:inline-block}.VERIFIED{color:var(--green);background:#123226}.PARTIAL{color:var(--amber);background:#332914}.FAILED{color:var(--red);background:#351b1e}.UNKNOWN{color:var(--blue);background:#152b38}.empty{padding:50px;text-align:center;color:var(--muted)}.providers{color:var(--muted);font-size:12px}.rid{font-family:ui-monospace,monospace;font-size:12px;color:var(--muted)}@media(max-width:1100px){.cards{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.shell{grid-template-columns:1fr}.side{display:none}.main{padding:20px}.key{width:210px}}@media(max-width:600px){.cards{grid-template-columns:1fr 1fr}.top{align-items:flex-start;flex-direction:column}.key{width:100%}.hint{text-align:left}th:nth-child(4),td:nth-child(4){display:none}}
</style></head><body><div class="shell"><aside class="side"><div class="logo">DoneProof</div><div class="navitem active">Assurance</div><a class="navitem" style="display:block;text-decoration:none" href="/docs">API reference</a><a class="navitem" style="display:block;text-decoration:none" href="/v1/capabilities">Capabilities</a></aside><main class="main"><div class="top"><div><h1>Outcome assurance</h1><div class="sub">Independent evidence for autonomous work</div></div><div><input id="key" class="key" type="password" autocomplete="off" placeholder="Workspace API key"><div class="hint">Stored for this browser session only</div></div></div>
<div class="cards"><div class="card"><div class="label">Verified rate</div><div id="verification_rate" class="value">—</div></div><div class="card"><div class="label">Total checked</div><div id="total" class="value">—</div></div><div class="card"><div class="label">Partial</div><div id="partial" class="value">—</div></div><div class="card"><div class="label">Failed</div><div id="failed" class="value">—</div></div><div class="card"><div class="label">Unknown</div><div id="unknown" class="value">—</div></div><div class="card"><div class="label">Avg verify time</div><div id="average_duration_ms" class="value">—</div></div></div>
<div class="tablewrap"><div class="tablehead">Recent verification receipts</div><div id="content"><div class="empty">Loading assurance data…</div></div></div></main></div>
<script>
const key=document.getElementById('key');key.value=sessionStorage.getItem('doneproof_key')||'';key.addEventListener('change',()=>{sessionStorage.setItem('doneproof_key',key.value);load()});
function headers(){return key.value?{'X-DoneProof-Key':key.value}:{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function load(){try{const [s,r]=await Promise.all([fetch('/v1/overview',{headers:headers()}),fetch('/v1/receipts?limit=30',{headers:headers()})]);if(!s.ok||!r.ok)throw new Error(s.status===401?'Enter a valid workspace API key':'Assurance API unavailable');const stats=await s.json(),receipts=await r.json();for(const k of ['total','partial','failed','unknown'])document.getElementById(k).textContent=stats[k.toUpperCase()]??stats[k]??0;document.getElementById('verification_rate').textContent=(stats.verification_rate??0)+'%';document.getElementById('average_duration_ms').textContent=Math.round(stats.average_duration_ms??0)+' ms';const c=document.getElementById('content');if(!receipts.length){c.innerHTML='<div class="empty">No verification receipts yet.</div>';return}c.innerHTML='<table><thead><tr><th>Verdict</th><th>Business outcome</th><th>Evidence</th><th>Assurance</th><th>Receipt</th><th>Verified</th></tr></thead><tbody>'+receipts.map(x=>`<tr><td><span class="badge ${x.verdict}">${x.verdict}</span></td><td class="task">${esc(x.task)}</td><td><div>${x.summary.passed}/${x.summary.total} conditions passed</div><div class="providers">${esc(x.summary.providers.join(' · '))}</div></td><td>${esc(x.assurance_level)}</td><td class="rid">${esc(x.receipt_id)}</td><td>${new Date(x.verified_at).toLocaleString()}</td></tr>`).join('')+'</tbody></table>'}catch(e){document.getElementById('content').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
load();
</script></body></html>"""


def certificate_html(receipt: VerificationReceipt) -> str:
    items = "".join(
        f"<tr><td>{html.escape(r.description)}</td><td><b>{html.escape(r.status.value)}</b></td><td>{html.escape(r.evidence.provider)}</td></tr>"
        for r in receipt.results
        if r.required
    )
    return f"""<!doctype html><html><head><meta charset='utf-8'><title>DoneProof receipt {html.escape(receipt.receipt_id)}</title><style>body{{font:15px/1.55 system-ui;max-width:850px;margin:60px auto;padding:0 24px;color:#16202a}}h1{{font-size:34px}}.v{{font-size:24px;font-weight:800}}table{{width:100%;border-collapse:collapse;margin:28px 0}}td,th{{padding:10px;border-bottom:1px solid #dfe6eb;text-align:left}}code{{word-break:break-all;color:#53626f}}.muted{{color:#687887}}</style></head><body><div class='muted'>DONEPROOF VERIFICATION RECEIPT</div><h1>{html.escape(receipt.task)}</h1><div class='v'>{html.escape(receipt.verdict.value)}</div><p><b>Assurance:</b> {html.escape(receipt.assurance_level)} · {receipt.summary.passed} of {receipt.summary.total} evaluated conditions passed. Verified {html.escape(receipt.verified_at.isoformat())}.</p><table><thead><tr><th>Required outcome</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{items}</tbody></table><p class='muted'>Receipt ID</p><code>{html.escape(receipt.receipt_id)}</code><p class='muted'>Completion contract hash</p><code>{html.escape(receipt.contract_hash)}</code><p class='muted'>SHA-256 receipt hash</p><code>{html.escape(receipt.receipt_hash)}</code><p class='muted'>Signing key</p><code>{html.escape(receipt.key_id)} · Ed25519</code><p class='muted'>This certificate summarizes the signed machine-readable receipt. Verify the JSON receipt against a DoneProof public key that your organization pinned through an independent channel.</p></body></html>"""
