// Generated by scripts/sdk_schemas.py. Do not edit.
export const schemas = {
  "AssuranceSession": {
    "$defs": {
      "BrowserProvenance": {
        "additionalProperties": false,
        "properties": {
          "assurance": {
            "const": "lower_than_authoritative_api",
            "default": "lower_than_authoritative_api",
            "title": "Assurance",
            "type": "string"
          },
          "authenticated": {
            "const": false,
            "default": false,
            "title": "Authenticated",
            "type": "boolean"
          },
          "check_revision": {
            "anyOf": [
              {
                "pattern": "^[a-f0-9]{64}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Check Revision"
          },
          "collector": {
            "const": "doneproof.chromium.v1",
            "default": "doneproof.chromium.v1",
            "title": "Collector",
            "type": "string"
          },
          "executor_supplied": {
            "const": false,
            "default": false,
            "title": "Executor Supplied",
            "type": "boolean"
          },
          "fresh_context": {
            "anyOf": [
              {
                "const": true,
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Fresh Context"
          },
          "kind": {
            "const": "browser_ui",
            "default": "browser_ui",
            "title": "Kind",
            "type": "string"
          },
          "outcome": {
            "default": "unavailable",
            "enum": [
              "recognized",
              "unavailable",
              "not_configured",
              "invalid_condition",
              "policy_changed",
              "api_required",
              "blocked_request",
              "login_or_challenge",
              "ambiguous_ui",
              "unstable_ui",
              "screenshot_unavailable",
              "browser_unavailable",
              "deadline"
            ],
            "title": "Outcome",
            "type": "string"
          },
          "recognized_state": {
            "anyOf": [
              {
                "pattern": "^[a-z][a-z0-9_-]{0,39}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Recognized State"
          },
          "samples": {
            "default": 0,
            "maximum": 3,
            "minimum": 0,
            "title": "Samples",
            "type": "integer"
          },
          "screenshot": {
            "anyOf": [
              {
                "$ref": "#/$defs/ScreenshotRef"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "session_id": {
            "anyOf": [
              {
                "pattern": "^bo_[a-f0-9]{32}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Session Id"
          }
        },
        "title": "BrowserProvenance",
        "type": "object"
      },
      "CallbackDelivery": {
        "properties": {
          "attempts": {
            "title": "Attempts",
            "type": "integer"
          },
          "error_code": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Error Code"
          },
          "state": {
            "enum": [
              "PENDING",
              "SENDING",
              "DELIVERED",
              "DEAD"
            ],
            "title": "State",
            "type": "string"
          }
        },
        "required": [
          "state",
          "attempts"
        ],
        "title": "CallbackDelivery",
        "type": "object"
      },
      "CompilationIssue": {
        "properties": {
          "category": {
            "enum": [
              "unsupported_provider",
              "missing_identifier",
              "ambiguous_resource",
              "unverifiable_outcome",
              "valid_contract"
            ],
            "title": "Category",
            "type": "string"
          },
          "code": {
            "title": "Code",
            "type": "string"
          },
          "condition_ids": {
            "items": {
              "type": "string"
            },
            "title": "Condition Ids",
            "type": "array"
          },
          "fields": {
            "items": {
              "type": "string"
            },
            "title": "Fields",
            "type": "array"
          },
          "message": {
            "title": "Message",
            "type": "string"
          }
        },
        "required": [
          "code",
          "category",
          "message"
        ],
        "title": "CompilationIssue",
        "type": "object"
      },
      "CompilationResult": {
        "properties": {
          "clarification_requirements": {
            "items": {
              "$ref": "#/$defs/CompilationIssue"
            },
            "title": "Clarification Requirements",
            "type": "array"
          },
          "contract": {
            "anyOf": [
              {
                "$ref": "#/$defs/CompletionContract"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "contract_quality": {
            "$ref": "#/$defs/ContractQuality"
          },
          "deterministic": {
            "default": true,
            "title": "Deterministic",
            "type": "boolean"
          },
          "latency_ms": {
            "default": 0,
            "title": "Latency Ms",
            "type": "number"
          },
          "schema_version": {
            "const": "2.0",
            "default": "2.0",
            "title": "Schema Version",
            "type": "string"
          },
          "selector_checks": {
            "items": {
              "$ref": "#/$defs/SelectorCheck"
            },
            "title": "Selector Checks",
            "type": "array"
          },
          "stages": {
            "items": {
              "type": "string"
            },
            "title": "Stages",
            "type": "array"
          },
          "status": {
            "enum": [
              "unsupported_provider",
              "missing_identifier",
              "ambiguous_resource",
              "unverifiable_outcome",
              "valid_contract"
            ],
            "title": "Status",
            "type": "string"
          },
          "usage": {
            "$ref": "#/$defs/CompilationUsage"
          }
        },
        "required": [
          "status",
          "contract_quality"
        ],
        "title": "CompilationResult",
        "type": "object"
      },
      "CompilationUsage": {
        "properties": {
          "cache_write_tokens": {
            "default": 0,
            "title": "Cache Write Tokens",
            "type": "integer"
          },
          "cached_input_tokens": {
            "default": 0,
            "title": "Cached Input Tokens",
            "type": "integer"
          },
          "complete": {
            "default": true,
            "title": "Complete",
            "type": "boolean"
          },
          "efforts": {
            "items": {
              "type": "string"
            },
            "title": "Efforts",
            "type": "array"
          },
          "escalation_reasons": {
            "items": {
              "type": "string"
            },
            "title": "Escalation Reasons",
            "type": "array"
          },
          "input_tokens": {
            "default": 0,
            "title": "Input Tokens",
            "type": "integer"
          },
          "model": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Model"
          },
          "output_tokens": {
            "default": 0,
            "title": "Output Tokens",
            "type": "integer"
          },
          "reasoning_tokens": {
            "default": 0,
            "title": "Reasoning Tokens",
            "type": "integer"
          }
        },
        "title": "CompilationUsage",
        "type": "object"
      },
      "CompletionContract": {
        "properties": {
          "assumptions": {
            "description": "Explicit assumptions used when translating intent into verifiable conditions.",
            "items": {
              "type": "string"
            },
            "maxItems": 30,
            "title": "Assumptions",
            "type": "array"
          },
          "created_at": {
            "description": "Contract creation timestamp.",
            "format": "date-time",
            "title": "Created At",
            "type": "string"
          },
          "id": {
            "description": "Immutable contract identifier within a workspace.",
            "title": "Id",
            "type": "string"
          },
          "postconditions": {
            "description": "Machine-checkable outcomes that define completion.",
            "items": {
              "$ref": "#/$defs/Postcondition"
            },
            "maxItems": 50,
            "minItems": 1,
            "title": "Postconditions",
            "type": "array"
          },
          "schema_version": {
            "default": "1.0",
            "description": "Completion-contract schema version.",
            "title": "Schema Version",
            "type": "string"
          },
          "task": {
            "description": "Requested business outcome in human-readable form.",
            "maxLength": 4000,
            "minLength": 3,
            "title": "Task",
            "type": "string"
          },
          "task_started_at": {
            "description": "Verification time boundary. Registered runs replace caller input with server time.",
            "format": "date-time",
            "title": "Task Started At",
            "type": "string"
          }
        },
        "required": [
          "task",
          "postconditions"
        ],
        "title": "CompletionContract",
        "type": "object"
      },
      "ConditionResult": {
        "properties": {
          "baseline_observed": {
            "anyOf": [
              {},
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Baseline Observed"
          },
          "baseline_status": {
            "anyOf": [
              {
                "$ref": "#/$defs/ConditionStatus"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "description": {
            "title": "Description",
            "type": "string"
          },
          "evidence": {
            "$ref": "#/$defs/Evidence"
          },
          "id": {
            "title": "Id",
            "type": "string"
          },
          "latency_ms": {
            "default": 0.0,
            "title": "Latency Ms",
            "type": "number"
          },
          "predicate": {
            "$ref": "#/$defs/Predicate"
          },
          "reason": {
            "title": "Reason",
            "type": "string"
          },
          "required": {
            "title": "Required",
            "type": "boolean"
          },
          "status": {
            "$ref": "#/$defs/ConditionStatus"
          },
          "transition_required": {
            "default": false,
            "title": "Transition Required",
            "type": "boolean"
          }
        },
        "required": [
          "id",
          "description",
          "required",
          "status",
          "predicate",
          "evidence",
          "reason"
        ],
        "title": "ConditionResult",
        "type": "object"
      },
      "ConditionStatus": {
        "enum": [
          "PASS",
          "FAIL",
          "UNKNOWN"
        ],
        "title": "ConditionStatus",
        "type": "string"
      },
      "ContractQuality": {
        "properties": {
          "confidence": {
            "maximum": 1,
            "minimum": 0,
            "title": "Confidence",
            "type": "number"
          },
          "confidence_basis": {
            "const": "deterministic_checks",
            "default": "deterministic_checks",
            "title": "Confidence Basis",
            "type": "string"
          },
          "confidence_calibrated": {
            "const": false,
            "default": false,
            "title": "Confidence Calibrated",
            "type": "boolean"
          },
          "confidence_scope": {
            "const": "contract_structure",
            "default": "contract_structure",
            "title": "Confidence Scope",
            "type": "string"
          },
          "evidence": {
            "const": false,
            "default": false,
            "title": "Evidence",
            "type": "boolean"
          },
          "requires_registration": {
            "default": true,
            "title": "Requires Registration",
            "type": "boolean"
          },
          "warnings": {
            "items": {
              "$ref": "#/$defs/CompilationIssue"
            },
            "title": "Warnings",
            "type": "array"
          }
        },
        "required": [
          "confidence"
        ],
        "title": "ContractQuality",
        "type": "object"
      },
      "DurableJob": {
        "properties": {
          "assurance_level": {
            "enum": [
              "registered",
              "submitted"
            ],
            "title": "Assurance Level",
            "type": "string"
          },
          "callback": {
            "anyOf": [
              {
                "$ref": "#/$defs/CallbackDelivery"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "condition_count": {
            "title": "Condition Count",
            "type": "integer"
          },
          "conditions": {
            "additionalProperties": {
              "type": "integer"
            },
            "title": "Conditions",
            "type": "object"
          },
          "created_at": {
            "title": "Created At",
            "type": "number"
          },
          "deadline_at": {
            "title": "Deadline At",
            "type": "number"
          },
          "finished_at": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Finished At"
          },
          "id": {
            "title": "Id",
            "type": "string"
          },
          "receipt_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Receipt Id"
          },
          "revision": {
            "title": "Revision",
            "type": "integer"
          },
          "started_at": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "title": "Started At"
          },
          "state": {
            "enum": [
              "QUEUED",
              "OBSERVING",
              "EVALUATING",
              "SIGNING",
              "COMPLETE",
              "PARTIAL_FAILURE",
              "EXPIRED",
              "INTERNAL_ERROR"
            ],
            "title": "State",
            "type": "string"
          },
          "terminal_reason": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Terminal Reason"
          }
        },
        "required": [
          "id",
          "state",
          "revision",
          "assurance_level",
          "condition_count",
          "created_at",
          "started_at",
          "finished_at",
          "deadline_at",
          "terminal_reason",
          "conditions",
          "receipt_id"
        ],
        "title": "DurableJob",
        "type": "object"
      },
      "Evidence": {
        "properties": {
          "fetched_at": {
            "format": "date-time",
            "title": "Fetched At",
            "type": "string"
          },
          "note": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Note"
          },
          "observed": {
            "anyOf": [
              {},
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Observed"
          },
          "provenance": {
            "anyOf": [
              {
                "$ref": "#/$defs/BrowserProvenance"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "provider": {
            "title": "Provider",
            "type": "string"
          },
          "selector": {
            "additionalProperties": true,
            "title": "Selector",
            "type": "object"
          },
          "source_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Source Url"
          }
        },
        "required": [
          "provider",
          "selector"
        ],
        "title": "Evidence",
        "type": "object"
      },
      "EvidenceAssurance": {
        "properties": {
          "assurance_level": {
            "enum": [
              "provider_declared",
              "lower_than_authoritative_api",
              "unavailable"
            ],
            "title": "Assurance Level",
            "type": "string"
          },
          "condition": {
            "title": "Condition",
            "type": "string"
          },
          "evidence_class": {
            "enum": [
              "provider_observation",
              "browser_ui",
              "unavailable"
            ],
            "title": "Evidence Class",
            "type": "string"
          },
          "provenance": {
            "anyOf": [
              {
                "$ref": "#/$defs/BrowserProvenance"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "provider": {
            "title": "Provider",
            "type": "string"
          }
        },
        "required": [
          "condition",
          "provider",
          "evidence_class",
          "assurance_level"
        ],
        "title": "EvidenceAssurance",
        "type": "object"
      },
      "Postcondition": {
        "properties": {
          "description": {
            "description": "Human-readable business outcome being verified.",
            "maxLength": 300,
            "minLength": 2,
            "title": "Description",
            "type": "string"
          },
          "id": {
            "description": "Stable condition identifier within the contract.",
            "maxLength": 64,
            "minLength": 1,
            "title": "Id",
            "type": "string"
          },
          "predicate": {
            "$ref": "#/$defs/Predicate",
            "description": "Deterministic check evaluated against normalized provider state."
          },
          "provider": {
            "description": "Evidence provider used for this condition; browser UI carries lower assurance than an authoritative API.",
            "pattern": "^[a-z][a-z0-9_]{0,63}$",
            "title": "Provider",
            "type": "string"
          },
          "require_change": {
            "default": false,
            "description": "Require a registered pre-execution false-to-true transition instead of state-only assurance.",
            "title": "Require Change",
            "type": "boolean"
          },
          "required": {
            "default": true,
            "description": "Required conditions determine the overall verdict.",
            "title": "Required",
            "type": "boolean"
          },
          "selector": {
            "additionalProperties": true,
            "description": "Provider-specific resource lookup constraints. Credentials must not be placed here.",
            "title": "Selector",
            "type": "object"
          }
        },
        "required": [
          "id",
          "description",
          "provider",
          "selector",
          "predicate"
        ],
        "title": "Postcondition",
        "type": "object"
      },
      "Predicate": {
        "properties": {
          "expected": {
            "anyOf": [
              {},
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Expected"
          },
          "op": {
            "enum": [
              "eq",
              "neq",
              "exists",
              "not_exists",
              "contains",
              "contains_all",
              "gte",
              "lte"
            ],
            "title": "Op",
            "type": "string"
          },
          "path": {
            "description": "Dot path into normalized provider state; blank means root.",
            "title": "Path",
            "type": "string"
          }
        },
        "required": [
          "op",
          "path"
        ],
        "title": "Predicate",
        "type": "object"
      },
      "ProviderBinding": {
        "properties": {
          "fingerprint": {
            "title": "Fingerprint",
            "type": "string"
          },
          "provider": {
            "title": "Provider",
            "type": "string"
          },
          "version": {
            "title": "Version",
            "type": "string"
          }
        },
        "required": [
          "provider",
          "version",
          "fingerprint"
        ],
        "title": "ProviderBinding",
        "type": "object"
      },
      "ReceiptLink": {
        "properties": {
          "previous_receipt_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Previous Receipt Id"
          },
          "receipt_hash": {
            "title": "Receipt Hash",
            "type": "string"
          },
          "receipt_id": {
            "title": "Receipt Id",
            "type": "string"
          },
          "verdict": {
            "$ref": "#/$defs/Verdict"
          },
          "verified_at": {
            "format": "date-time",
            "title": "Verified At",
            "type": "string"
          }
        },
        "required": [
          "receipt_id",
          "receipt_hash",
          "previous_receipt_id",
          "verdict",
          "verified_at"
        ],
        "title": "ReceiptLink",
        "type": "object"
      },
      "RecoveryInfo": {
        "properties": {
          "attempt": {
            "default": 0,
            "maximum": 20,
            "minimum": 0,
            "title": "Attempt",
            "type": "integer"
          },
          "chain_id": {
            "title": "Chain Id",
            "type": "string"
          },
          "oscillating_conditions": {
            "items": {
              "type": "string"
            },
            "title": "Oscillating Conditions",
            "type": "array"
          },
          "repeated_failures": {
            "items": {
              "type": "string"
            },
            "title": "Repeated Failures",
            "type": "array"
          }
        },
        "required": [
          "chain_id"
        ],
        "title": "RecoveryInfo",
        "type": "object"
      },
      "Remediation": {
        "properties": {
          "action_hint": {
            "title": "Action Hint",
            "type": "string"
          },
          "code": {
            "title": "Code",
            "type": "string"
          },
          "condition": {
            "title": "Condition",
            "type": "string"
          },
          "expected": {
            "default": null,
            "title": "Expected"
          },
          "kind": {
            "const": "doneproof.remediation",
            "default": "doneproof.remediation",
            "title": "Kind",
            "type": "string"
          },
          "observed": {
            "default": null,
            "title": "Observed"
          },
          "retryable": {
            "title": "Retryable",
            "type": "boolean"
          },
          "reverify_after": {
            "enum": [
              "external_action",
              "authoritative_evidence",
              "new_registered_run",
              "contract_revision"
            ],
            "title": "Reverify After",
            "type": "string"
          },
          "status": {
            "enum": [
              "FAIL",
              "UNKNOWN"
            ],
            "title": "Status",
            "type": "string"
          }
        },
        "required": [
          "condition",
          "status",
          "retryable",
          "code",
          "action_hint",
          "reverify_after"
        ],
        "title": "Remediation",
        "type": "object"
      },
      "ScreenshotRef": {
        "additionalProperties": false,
        "properties": {
          "artifact_id": {
            "pattern": "^bs_[a-f0-9]{32}$",
            "title": "Artifact Id",
            "type": "string"
          },
          "bytes": {
            "exclusiveMinimum": 0,
            "maximum": 65536,
            "title": "Bytes",
            "type": "integer"
          },
          "encrypted": {
            "const": true,
            "default": true,
            "title": "Encrypted",
            "type": "boolean"
          },
          "expires_at": {
            "title": "Expires At",
            "type": "integer"
          },
          "media_type": {
            "const": "image/png",
            "default": "image/png",
            "title": "Media Type",
            "type": "string"
          },
          "sha256": {
            "pattern": "^[a-f0-9]{64}$",
            "title": "Sha256",
            "type": "string"
          }
        },
        "required": [
          "artifact_id",
          "sha256",
          "bytes",
          "expires_at"
        ],
        "title": "ScreenshotRef",
        "type": "object"
      },
      "SelectorCheck": {
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "condition_ids": {
            "items": {
              "type": "string"
            },
            "title": "Condition Ids",
            "type": "array"
          },
          "status": {
            "enum": [
              "resolved",
              "deferred",
              "ambiguous",
              "unavailable",
              "missing"
            ],
            "title": "Status",
            "type": "string"
          }
        },
        "required": [
          "condition_ids",
          "status",
          "code"
        ],
        "title": "SelectorCheck",
        "type": "object"
      },
      "Verdict": {
        "enum": [
          "VERIFIED",
          "PARTIAL",
          "FAILED",
          "UNKNOWN"
        ],
        "title": "Verdict",
        "type": "string"
      },
      "VerificationReceipt": {
        "properties": {
          "assurance_level": {
            "default": "submitted",
            "description": "Whether DoneProof established the assurance boundary before execution.",
            "enum": [
              "registered",
              "submitted"
            ],
            "title": "Assurance Level",
            "type": "string"
          },
          "contract_hash": {
            "default": "",
            "description": "SHA-256 of the exact canonical completion contract.",
            "title": "Contract Hash",
            "type": "string"
          },
          "contract_id": {
            "description": "Completion contract verified by this receipt.",
            "title": "Contract Id",
            "type": "string"
          },
          "duration_ms": {
            "default": 0.0,
            "title": "Duration Ms",
            "type": "number"
          },
          "key_id": {
            "default": "",
            "title": "Key Id",
            "type": "string"
          },
          "previous_receipt_hash": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Previous Receipt Hash"
          },
          "previous_receipt_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Previous Receipt Id"
          },
          "public_key": {
            "default": "",
            "title": "Public Key",
            "type": "string"
          },
          "receipt_hash": {
            "default": "",
            "title": "Receipt Hash",
            "type": "string"
          },
          "receipt_id": {
            "description": "Unique verification receipt identifier.",
            "title": "Receipt Id",
            "type": "string"
          },
          "recovery": {
            "anyOf": [
              {
                "$ref": "#/$defs/RecoveryInfo"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "remediation": {
            "items": {
              "$ref": "#/$defs/Remediation"
            },
            "title": "Remediation",
            "type": "array"
          },
          "results": {
            "items": {
              "$ref": "#/$defs/ConditionResult"
            },
            "title": "Results",
            "type": "array"
          },
          "schema_version": {
            "default": "1.0",
            "description": "Verification-receipt schema version.",
            "title": "Schema Version",
            "type": "string"
          },
          "signature": {
            "default": "",
            "title": "Signature",
            "type": "string"
          },
          "signature_alg": {
            "default": "Ed25519",
            "title": "Signature Alg",
            "type": "string"
          },
          "summary": {
            "$ref": "#/$defs/VerificationSummary"
          },
          "task": {
            "description": "Human-readable requested outcome copied from the contract.",
            "title": "Task",
            "type": "string"
          },
          "verdict": {
            "$ref": "#/$defs/Verdict"
          },
          "verified_at": {
            "format": "date-time",
            "title": "Verified At",
            "type": "string"
          }
        },
        "required": [
          "contract_id",
          "task",
          "verdict",
          "summary",
          "results"
        ],
        "title": "VerificationReceipt",
        "type": "object"
      },
      "VerificationSummary": {
        "properties": {
          "failed": {
            "title": "Failed",
            "type": "integer"
          },
          "passed": {
            "title": "Passed",
            "type": "integer"
          },
          "providers": {
            "items": {
              "type": "string"
            },
            "title": "Providers",
            "type": "array"
          },
          "required": {
            "title": "Required",
            "type": "integer"
          },
          "total": {
            "title": "Total",
            "type": "integer"
          },
          "unknown": {
            "title": "Unknown",
            "type": "integer"
          }
        },
        "required": [
          "total",
          "required",
          "passed",
          "failed",
          "unknown",
          "providers"
        ],
        "title": "VerificationSummary",
        "type": "object"
      }
    },
    "properties": {
      "baselines": {
        "items": {
          "$ref": "#/$defs/ConditionResult"
        },
        "title": "Baselines",
        "type": "array"
      },
      "can_reverify": {
        "default": false,
        "title": "Can Reverify",
        "type": "boolean"
      },
      "compiler": {
        "anyOf": [
          {
            "$ref": "#/$defs/CompilationResult"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "contract": {
        "anyOf": [
          {
            "$ref": "#/$defs/CompletionContract"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "created_at": {
        "format": "date-time",
        "title": "Created At",
        "type": "string"
      },
      "current_job_id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Current Job Id"
      },
      "evidence": {
        "items": {
          "$ref": "#/$defs/EvidenceAssurance"
        },
        "title": "Evidence",
        "type": "array"
      },
      "id": {
        "title": "Id",
        "type": "string"
      },
      "jobs": {
        "items": {
          "$ref": "#/$defs/DurableJob"
        },
        "title": "Jobs",
        "type": "array"
      },
      "lineage": {
        "items": {
          "$ref": "#/$defs/ReceiptLink"
        },
        "title": "Lineage",
        "type": "array"
      },
      "protocol_version": {
        "const": "1.0",
        "default": "1.0",
        "title": "Protocol Version",
        "type": "string"
      },
      "providers": {
        "items": {
          "$ref": "#/$defs/ProviderBinding"
        },
        "title": "Providers",
        "type": "array"
      },
      "receipt": {
        "anyOf": [
          {
            "$ref": "#/$defs/VerificationReceipt"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "remediation": {
        "items": {
          "$ref": "#/$defs/Remediation"
        },
        "title": "Remediation",
        "type": "array"
      },
      "signed_payload_b64": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Signed Payload B64"
      },
      "state": {
        "enum": [
          "PREPARING",
          "PREPARATION_FAILED",
          "NEEDS_CLARIFICATION",
          "READY_FOR_EXECUTION",
          "VERIFYING",
          "VERIFIED",
          "PARTIAL",
          "FAILED",
          "UNKNOWN",
          "REPAIR_PENDING",
          "REVERIFYING"
        ],
        "title": "State",
        "type": "string"
      },
      "task": {
        "title": "Task",
        "type": "string"
      },
      "trusted_task_started_at": {
        "anyOf": [
          {
            "format": "date-time",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Trusted Task Started At"
      },
      "updated_at": {
        "format": "date-time",
        "title": "Updated At",
        "type": "string"
      },
      "verdict": {
        "anyOf": [
          {
            "$ref": "#/$defs/Verdict"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "workspace": {
        "title": "Workspace",
        "type": "string"
      }
    },
    "required": [
      "id",
      "workspace",
      "task",
      "state",
      "created_at",
      "updated_at"
    ],
    "title": "AssuranceSession",
    "type": "object"
  },
  "CapabilityResponse": {
    "$defs": {
      "ProviderCapability": {
        "properties": {
          "description": {
            "title": "Description",
            "type": "string"
          },
          "provider": {
            "title": "Provider",
            "type": "string"
          },
          "status": {
            "enum": [
              "available",
              "configuration_required",
              "disabled"
            ],
            "title": "Status",
            "type": "string"
          }
        },
        "required": [
          "provider",
          "status",
          "description"
        ],
        "title": "ProviderCapability",
        "type": "object"
      }
    },
    "properties": {
      "compiler": {
        "enum": [
          "available",
          "configuration_required"
        ],
        "title": "Compiler",
        "type": "string"
      },
      "environment": {
        "title": "Environment",
        "type": "string"
      },
      "providers": {
        "items": {
          "$ref": "#/$defs/ProviderCapability"
        },
        "title": "Providers",
        "type": "array"
      },
      "signing_key_id": {
        "title": "Signing Key Id",
        "type": "string"
      },
      "version": {
        "title": "Version",
        "type": "string"
      }
    },
    "required": [
      "version",
      "environment",
      "compiler",
      "signing_key_id",
      "providers"
    ],
    "title": "CapabilityResponse",
    "type": "object"
  },
  "CompilationResult": {
    "$defs": {
      "CompilationIssue": {
        "properties": {
          "category": {
            "enum": [
              "unsupported_provider",
              "missing_identifier",
              "ambiguous_resource",
              "unverifiable_outcome",
              "valid_contract"
            ],
            "title": "Category",
            "type": "string"
          },
          "code": {
            "title": "Code",
            "type": "string"
          },
          "condition_ids": {
            "items": {
              "type": "string"
            },
            "title": "Condition Ids",
            "type": "array"
          },
          "fields": {
            "items": {
              "type": "string"
            },
            "title": "Fields",
            "type": "array"
          },
          "message": {
            "title": "Message",
            "type": "string"
          }
        },
        "required": [
          "code",
          "category",
          "message"
        ],
        "title": "CompilationIssue",
        "type": "object"
      },
      "CompilationUsage": {
        "properties": {
          "cache_write_tokens": {
            "default": 0,
            "title": "Cache Write Tokens",
            "type": "integer"
          },
          "cached_input_tokens": {
            "default": 0,
            "title": "Cached Input Tokens",
            "type": "integer"
          },
          "complete": {
            "default": true,
            "title": "Complete",
            "type": "boolean"
          },
          "efforts": {
            "items": {
              "type": "string"
            },
            "title": "Efforts",
            "type": "array"
          },
          "escalation_reasons": {
            "items": {
              "type": "string"
            },
            "title": "Escalation Reasons",
            "type": "array"
          },
          "input_tokens": {
            "default": 0,
            "title": "Input Tokens",
            "type": "integer"
          },
          "model": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Model"
          },
          "output_tokens": {
            "default": 0,
            "title": "Output Tokens",
            "type": "integer"
          },
          "reasoning_tokens": {
            "default": 0,
            "title": "Reasoning Tokens",
            "type": "integer"
          }
        },
        "title": "CompilationUsage",
        "type": "object"
      },
      "CompletionContract": {
        "properties": {
          "assumptions": {
            "description": "Explicit assumptions used when translating intent into verifiable conditions.",
            "items": {
              "type": "string"
            },
            "maxItems": 30,
            "title": "Assumptions",
            "type": "array"
          },
          "created_at": {
            "description": "Contract creation timestamp.",
            "format": "date-time",
            "title": "Created At",
            "type": "string"
          },
          "id": {
            "description": "Immutable contract identifier within a workspace.",
            "title": "Id",
            "type": "string"
          },
          "postconditions": {
            "description": "Machine-checkable outcomes that define completion.",
            "items": {
              "$ref": "#/$defs/Postcondition"
            },
            "maxItems": 50,
            "minItems": 1,
            "title": "Postconditions",
            "type": "array"
          },
          "schema_version": {
            "default": "1.0",
            "description": "Completion-contract schema version.",
            "title": "Schema Version",
            "type": "string"
          },
          "task": {
            "description": "Requested business outcome in human-readable form.",
            "maxLength": 4000,
            "minLength": 3,
            "title": "Task",
            "type": "string"
          },
          "task_started_at": {
            "description": "Verification time boundary. Registered runs replace caller input with server time.",
            "format": "date-time",
            "title": "Task Started At",
            "type": "string"
          }
        },
        "required": [
          "task",
          "postconditions"
        ],
        "title": "CompletionContract",
        "type": "object"
      },
      "ContractQuality": {
        "properties": {
          "confidence": {
            "maximum": 1,
            "minimum": 0,
            "title": "Confidence",
            "type": "number"
          },
          "confidence_basis": {
            "const": "deterministic_checks",
            "default": "deterministic_checks",
            "title": "Confidence Basis",
            "type": "string"
          },
          "confidence_calibrated": {
            "const": false,
            "default": false,
            "title": "Confidence Calibrated",
            "type": "boolean"
          },
          "confidence_scope": {
            "const": "contract_structure",
            "default": "contract_structure",
            "title": "Confidence Scope",
            "type": "string"
          },
          "evidence": {
            "const": false,
            "default": false,
            "title": "Evidence",
            "type": "boolean"
          },
          "requires_registration": {
            "default": true,
            "title": "Requires Registration",
            "type": "boolean"
          },
          "warnings": {
            "items": {
              "$ref": "#/$defs/CompilationIssue"
            },
            "title": "Warnings",
            "type": "array"
          }
        },
        "required": [
          "confidence"
        ],
        "title": "ContractQuality",
        "type": "object"
      },
      "Postcondition": {
        "properties": {
          "description": {
            "description": "Human-readable business outcome being verified.",
            "maxLength": 300,
            "minLength": 2,
            "title": "Description",
            "type": "string"
          },
          "id": {
            "description": "Stable condition identifier within the contract.",
            "maxLength": 64,
            "minLength": 1,
            "title": "Id",
            "type": "string"
          },
          "predicate": {
            "$ref": "#/$defs/Predicate",
            "description": "Deterministic check evaluated against normalized provider state."
          },
          "provider": {
            "description": "Evidence provider used for this condition; browser UI carries lower assurance than an authoritative API.",
            "pattern": "^[a-z][a-z0-9_]{0,63}$",
            "title": "Provider",
            "type": "string"
          },
          "require_change": {
            "default": false,
            "description": "Require a registered pre-execution false-to-true transition instead of state-only assurance.",
            "title": "Require Change",
            "type": "boolean"
          },
          "required": {
            "default": true,
            "description": "Required conditions determine the overall verdict.",
            "title": "Required",
            "type": "boolean"
          },
          "selector": {
            "additionalProperties": true,
            "description": "Provider-specific resource lookup constraints. Credentials must not be placed here.",
            "title": "Selector",
            "type": "object"
          }
        },
        "required": [
          "id",
          "description",
          "provider",
          "selector",
          "predicate"
        ],
        "title": "Postcondition",
        "type": "object"
      },
      "Predicate": {
        "properties": {
          "expected": {
            "anyOf": [
              {},
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Expected"
          },
          "op": {
            "enum": [
              "eq",
              "neq",
              "exists",
              "not_exists",
              "contains",
              "contains_all",
              "gte",
              "lte"
            ],
            "title": "Op",
            "type": "string"
          },
          "path": {
            "description": "Dot path into normalized provider state; blank means root.",
            "title": "Path",
            "type": "string"
          }
        },
        "required": [
          "op",
          "path"
        ],
        "title": "Predicate",
        "type": "object"
      },
      "SelectorCheck": {
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "condition_ids": {
            "items": {
              "type": "string"
            },
            "title": "Condition Ids",
            "type": "array"
          },
          "status": {
            "enum": [
              "resolved",
              "deferred",
              "ambiguous",
              "unavailable",
              "missing"
            ],
            "title": "Status",
            "type": "string"
          }
        },
        "required": [
          "condition_ids",
          "status",
          "code"
        ],
        "title": "SelectorCheck",
        "type": "object"
      }
    },
    "properties": {
      "clarification_requirements": {
        "items": {
          "$ref": "#/$defs/CompilationIssue"
        },
        "title": "Clarification Requirements",
        "type": "array"
      },
      "contract": {
        "anyOf": [
          {
            "$ref": "#/$defs/CompletionContract"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "contract_quality": {
        "$ref": "#/$defs/ContractQuality"
      },
      "deterministic": {
        "default": true,
        "title": "Deterministic",
        "type": "boolean"
      },
      "latency_ms": {
        "default": 0,
        "title": "Latency Ms",
        "type": "number"
      },
      "schema_version": {
        "const": "2.0",
        "default": "2.0",
        "title": "Schema Version",
        "type": "string"
      },
      "selector_checks": {
        "items": {
          "$ref": "#/$defs/SelectorCheck"
        },
        "title": "Selector Checks",
        "type": "array"
      },
      "stages": {
        "items": {
          "type": "string"
        },
        "title": "Stages",
        "type": "array"
      },
      "status": {
        "enum": [
          "unsupported_provider",
          "missing_identifier",
          "ambiguous_resource",
          "unverifiable_outcome",
          "valid_contract"
        ],
        "title": "Status",
        "type": "string"
      },
      "usage": {
        "$ref": "#/$defs/CompilationUsage"
      }
    },
    "required": [
      "status",
      "contract_quality"
    ],
    "title": "CompilationResult",
    "type": "object"
  },
  "CompletionEvent": {
    "additionalProperties": false,
    "properties": {
      "event_id": {
        "pattern": "^ve_[a-f0-9]{32}$",
        "title": "Event Id",
        "type": "string"
      },
      "finished_at": {
        "minimum": 0,
        "title": "Finished At",
        "type": "number"
      },
      "job_id": {
        "pattern": "^vj_[a-f0-9]{32}$",
        "title": "Job Id",
        "type": "string"
      },
      "receipt_id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Receipt Id"
      },
      "state": {
        "enum": [
          "COMPLETE",
          "PARTIAL_FAILURE",
          "EXPIRED",
          "INTERNAL_ERROR"
        ],
        "title": "State",
        "type": "string"
      }
    },
    "required": [
      "event_id",
      "job_id",
      "state",
      "receipt_id",
      "finished_at"
    ],
    "title": "CompletionEvent",
    "type": "object"
  },
  "ConnectionList": {
    "$defs": {
      "ConnectionView": {
        "properties": {
          "account_label": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Account Label"
          },
          "created_at": {
            "title": "Created At",
            "type": "integer"
          },
          "error_code": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Error Code"
          },
          "expires_at": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Expires At"
          },
          "id": {
            "title": "Id",
            "type": "string"
          },
          "last_checked_at": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Last Checked At"
          },
          "provider": {
            "title": "Provider",
            "type": "string"
          },
          "refresh_expires_at": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "title": "Refresh Expires At"
          },
          "revision": {
            "default": 0,
            "title": "Revision",
            "type": "integer"
          },
          "revocation_pending": {
            "title": "Revocation Pending",
            "type": "boolean"
          },
          "scopes": {
            "items": {
              "type": "string"
            },
            "title": "Scopes",
            "type": "array"
          },
          "state": {
            "enum": [
              "connected",
              "expired",
              "reconnect_required",
              "disabled",
              "error"
            ],
            "title": "State",
            "type": "string"
          },
          "updated_at": {
            "title": "Updated At",
            "type": "integer"
          }
        },
        "required": [
          "id",
          "provider",
          "state",
          "account_label",
          "expires_at",
          "refresh_expires_at",
          "last_checked_at",
          "error_code",
          "created_at",
          "updated_at",
          "scopes",
          "revocation_pending"
        ],
        "title": "ConnectionView",
        "type": "object"
      },
      "OnboardingProvider": {
        "properties": {
          "installation_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Installation Url"
          },
          "onboarding_available": {
            "title": "Onboarding Available",
            "type": "boolean"
          },
          "provider": {
            "title": "Provider",
            "type": "string"
          }
        },
        "required": [
          "provider",
          "onboarding_available",
          "installation_url"
        ],
        "title": "OnboardingProvider",
        "type": "object"
      }
    },
    "properties": {
      "connections": {
        "items": {
          "$ref": "#/$defs/ConnectionView"
        },
        "title": "Connections",
        "type": "array"
      },
      "providers": {
        "items": {
          "$ref": "#/$defs/OnboardingProvider"
        },
        "title": "Providers",
        "type": "array"
      }
    },
    "required": [
      "connections",
      "providers"
    ],
    "title": "ConnectionList",
    "type": "object"
  },
  "ConnectionOnboarding": {
    "properties": {
      "administrator_login_required": {
        "const": true,
        "default": true,
        "title": "Administrator Login Required",
        "type": "boolean"
      },
      "authorization_url": {
        "title": "Authorization Url",
        "type": "string"
      },
      "mode": {
        "const": "trusted_browser_settings",
        "default": "trusted_browser_settings",
        "title": "Mode",
        "type": "string"
      }
    },
    "required": [
      "authorization_url"
    ],
    "title": "ConnectionOnboarding",
    "type": "object"
  },
  "ConnectionView": {
    "properties": {
      "account_label": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Account Label"
      },
      "created_at": {
        "title": "Created At",
        "type": "integer"
      },
      "error_code": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Error Code"
      },
      "expires_at": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "title": "Expires At"
      },
      "id": {
        "title": "Id",
        "type": "string"
      },
      "last_checked_at": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "title": "Last Checked At"
      },
      "provider": {
        "title": "Provider",
        "type": "string"
      },
      "refresh_expires_at": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "title": "Refresh Expires At"
      },
      "revision": {
        "default": 0,
        "title": "Revision",
        "type": "integer"
      },
      "revocation_pending": {
        "title": "Revocation Pending",
        "type": "boolean"
      },
      "scopes": {
        "items": {
          "type": "string"
        },
        "title": "Scopes",
        "type": "array"
      },
      "state": {
        "enum": [
          "connected",
          "expired",
          "reconnect_required",
          "disabled",
          "error"
        ],
        "title": "State",
        "type": "string"
      },
      "updated_at": {
        "title": "Updated At",
        "type": "integer"
      }
    },
    "required": [
      "id",
      "provider",
      "state",
      "account_label",
      "expires_at",
      "refresh_expires_at",
      "last_checked_at",
      "error_code",
      "created_at",
      "updated_at",
      "scopes",
      "revocation_pending"
    ],
    "title": "ConnectionView",
    "type": "object"
  },
  "DurableJob": {
    "$defs": {
      "CallbackDelivery": {
        "properties": {
          "attempts": {
            "title": "Attempts",
            "type": "integer"
          },
          "error_code": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Error Code"
          },
          "state": {
            "enum": [
              "PENDING",
              "SENDING",
              "DELIVERED",
              "DEAD"
            ],
            "title": "State",
            "type": "string"
          }
        },
        "required": [
          "state",
          "attempts"
        ],
        "title": "CallbackDelivery",
        "type": "object"
      }
    },
    "properties": {
      "assurance_level": {
        "enum": [
          "registered",
          "submitted"
        ],
        "title": "Assurance Level",
        "type": "string"
      },
      "callback": {
        "anyOf": [
          {
            "$ref": "#/$defs/CallbackDelivery"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "condition_count": {
        "title": "Condition Count",
        "type": "integer"
      },
      "conditions": {
        "additionalProperties": {
          "type": "integer"
        },
        "title": "Conditions",
        "type": "object"
      },
      "created_at": {
        "title": "Created At",
        "type": "number"
      },
      "deadline_at": {
        "title": "Deadline At",
        "type": "number"
      },
      "finished_at": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "null"
          }
        ],
        "title": "Finished At"
      },
      "id": {
        "title": "Id",
        "type": "string"
      },
      "receipt_id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Receipt Id"
      },
      "revision": {
        "title": "Revision",
        "type": "integer"
      },
      "started_at": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "null"
          }
        ],
        "title": "Started At"
      },
      "state": {
        "enum": [
          "QUEUED",
          "OBSERVING",
          "EVALUATING",
          "SIGNING",
          "COMPLETE",
          "PARTIAL_FAILURE",
          "EXPIRED",
          "INTERNAL_ERROR"
        ],
        "title": "State",
        "type": "string"
      },
      "terminal_reason": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "title": "Terminal Reason"
      }
    },
    "required": [
      "id",
      "state",
      "revision",
      "assurance_level",
      "condition_count",
      "created_at",
      "started_at",
      "finished_at",
      "deadline_at",
      "terminal_reason",
      "conditions",
      "receipt_id"
    ],
    "title": "DurableJob",
    "type": "object"
  },
  "PrepareSession": {
    "$defs": {
      "JsonValue": {}
    },
    "additionalProperties": false,
    "properties": {
      "context": {
        "additionalProperties": {
          "$ref": "#/$defs/JsonValue"
        },
        "title": "Context",
        "type": "object"
      },
      "task": {
        "maxLength": 4000,
        "minLength": 3,
        "title": "Task",
        "type": "string"
      }
    },
    "required": [
      "task"
    ],
    "title": "PrepareSession",
    "type": "object"
  },
  "ProviderCatalog": {
    "$defs": {
      "Authentication": {
        "additionalProperties": false,
        "properties": {
          "authorization_origin": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Authorization Origin"
          },
          "mode": {
            "enum": [
              "managed_oauth",
              "signed_events",
              "none"
            ],
            "title": "Mode",
            "type": "string"
          },
          "onboarding_order": {
            "default": 100,
            "maximum": 1000,
            "minimum": 0,
            "title": "Onboarding Order",
            "type": "integer"
          },
          "public_read": {
            "default": false,
            "title": "Public Read",
            "type": "boolean"
          },
          "refresh_required": {
            "default": false,
            "title": "Refresh Required",
            "type": "boolean"
          },
          "requirements": {
            "items": {
              "type": "string"
            },
            "title": "Requirements",
            "type": "array"
          }
        },
        "required": [
          "mode",
          "requirements"
        ],
        "title": "Authentication",
        "type": "object"
      },
      "Discovery": {
        "additionalProperties": false,
        "properties": {
          "boundary_field": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Boundary Field"
          },
          "event_driven": {
            "default": false,
            "title": "Event Driven",
            "type": "boolean"
          },
          "identity_field": {
            "title": "Identity Field",
            "type": "string"
          },
          "identity_schema": {
            "additionalProperties": true,
            "title": "Identity Schema",
            "type": "object"
          },
          "scope_fields": {
            "default": [],
            "items": {
              "type": "string"
            },
            "title": "Scope Fields",
            "type": "array"
          },
          "supported": {
            "title": "Supported",
            "type": "boolean"
          }
        },
        "required": [
          "supported",
          "identity_field",
          "identity_schema"
        ],
        "title": "Discovery",
        "type": "object"
      },
      "ProviderDocument": {
        "additionalProperties": false,
        "properties": {
          "authentication": {
            "$ref": "#/$defs/Authentication"
          },
          "baseline_support": {
            "title": "Baseline Support",
            "type": "boolean"
          },
          "compiler_instructions": {
            "default": "",
            "maxLength": 8000,
            "title": "Compiler Instructions",
            "type": "string"
          },
          "context_fields": {
            "default": [],
            "items": {
              "type": "string"
            },
            "title": "Context Fields",
            "type": "array"
          },
          "description": {
            "maxLength": 1000,
            "minLength": 1,
            "title": "Description",
            "type": "string"
          },
          "discovery": {
            "$ref": "#/$defs/Discovery"
          },
          "display_name": {
            "maxLength": 100,
            "minLength": 1,
            "title": "Display Name",
            "type": "string"
          },
          "evidence_schema": {
            "additionalProperties": true,
            "title": "Evidence Schema",
            "type": "object"
          },
          "evidence_sensitivity": {
            "enum": [
              "public",
              "internal",
              "confidential",
              "restricted"
            ],
            "title": "Evidence Sensitivity",
            "type": "string"
          },
          "fingerprint": {
            "pattern": "^[a-f0-9]{64}$",
            "title": "Fingerprint",
            "type": "string"
          },
          "provider_id": {
            "pattern": "^[a-z][a-z0-9_]{0,63}$",
            "title": "Provider Id",
            "type": "string"
          },
          "rate_limit": {
            "$ref": "#/$defs/RateLimitPolicy"
          },
          "resource_types": {
            "items": {
              "type": "string"
            },
            "minItems": 1,
            "title": "Resource Types",
            "type": "array"
          },
          "sdk_version": {
            "const": 1,
            "default": 1,
            "title": "Sdk Version",
            "type": "integer"
          },
          "selector_schema": {
            "additionalProperties": true,
            "title": "Selector Schema",
            "type": "object"
          },
          "sensitive_paths": {
            "default": [],
            "items": {
              "type": "string"
            },
            "title": "Sensitive Paths",
            "type": "array"
          },
          "supported_predicates": {
            "items": {
              "type": "string"
            },
            "minItems": 1,
            "title": "Supported Predicates",
            "type": "array"
          },
          "transition_support": {
            "title": "Transition Support",
            "type": "boolean"
          },
          "version": {
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
            "title": "Version",
            "type": "string"
          }
        },
        "required": [
          "provider_id",
          "version",
          "display_name",
          "description",
          "resource_types",
          "evidence_schema",
          "selector_schema",
          "supported_predicates",
          "discovery",
          "baseline_support",
          "transition_support",
          "authentication",
          "rate_limit",
          "evidence_sensitivity",
          "fingerprint"
        ],
        "title": "ProviderDocument",
        "type": "object"
      },
      "RateLimitPolicy": {
        "additionalProperties": false,
        "properties": {
          "attempts": {
            "maximum": 8,
            "minimum": 1,
            "title": "Attempts",
            "type": "integer"
          },
          "base_seconds": {
            "exclusiveMinimum": 0,
            "maximum": 300,
            "title": "Base Seconds",
            "type": "number"
          },
          "cap_seconds": {
            "exclusiveMinimum": 0,
            "maximum": 3600,
            "title": "Cap Seconds",
            "type": "number"
          },
          "concurrency": {
            "maximum": 64,
            "minimum": 1,
            "title": "Concurrency",
            "type": "integer"
          },
          "preflight_concurrency": {
            "maximum": 64,
            "minimum": 1,
            "title": "Preflight Concurrency",
            "type": "integer"
          }
        },
        "required": [
          "concurrency",
          "preflight_concurrency",
          "attempts",
          "base_seconds",
          "cap_seconds"
        ],
        "title": "RateLimitPolicy",
        "type": "object"
      }
    },
    "properties": {
      "providers": {
        "items": {
          "$ref": "#/$defs/ProviderDocument"
        },
        "title": "Providers",
        "type": "array"
      },
      "sdk_version": {
        "const": 1,
        "title": "Sdk Version",
        "type": "integer"
      }
    },
    "required": [
      "sdk_version",
      "providers"
    ],
    "title": "ProviderCatalog",
    "type": "object"
  },
  "ReverifySession": {
    "additionalProperties": false,
    "properties": {
      "callback_id": {
        "anyOf": [
          {
            "pattern": "^[A-Za-z0-9_-]{1,64}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Callback Id"
      },
      "deadline_seconds": {
        "default": 300,
        "maximum": 3600,
        "minimum": 1,
        "title": "Deadline Seconds",
        "type": "integer"
      },
      "previous_receipt_id": {
        "pattern": "^vr_[a-f0-9]{20,32}$",
        "title": "Previous Receipt Id",
        "type": "string"
      }
    },
    "required": [
      "previous_receipt_id"
    ],
    "title": "ReverifySession",
    "type": "object"
  },
  "VerificationReceipt": {
    "$defs": {
      "BrowserProvenance": {
        "additionalProperties": false,
        "properties": {
          "assurance": {
            "const": "lower_than_authoritative_api",
            "default": "lower_than_authoritative_api",
            "title": "Assurance",
            "type": "string"
          },
          "authenticated": {
            "const": false,
            "default": false,
            "title": "Authenticated",
            "type": "boolean"
          },
          "check_revision": {
            "anyOf": [
              {
                "pattern": "^[a-f0-9]{64}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Check Revision"
          },
          "collector": {
            "const": "doneproof.chromium.v1",
            "default": "doneproof.chromium.v1",
            "title": "Collector",
            "type": "string"
          },
          "executor_supplied": {
            "const": false,
            "default": false,
            "title": "Executor Supplied",
            "type": "boolean"
          },
          "fresh_context": {
            "anyOf": [
              {
                "const": true,
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Fresh Context"
          },
          "kind": {
            "const": "browser_ui",
            "default": "browser_ui",
            "title": "Kind",
            "type": "string"
          },
          "outcome": {
            "default": "unavailable",
            "enum": [
              "recognized",
              "unavailable",
              "not_configured",
              "invalid_condition",
              "policy_changed",
              "api_required",
              "blocked_request",
              "login_or_challenge",
              "ambiguous_ui",
              "unstable_ui",
              "screenshot_unavailable",
              "browser_unavailable",
              "deadline"
            ],
            "title": "Outcome",
            "type": "string"
          },
          "recognized_state": {
            "anyOf": [
              {
                "pattern": "^[a-z][a-z0-9_-]{0,39}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Recognized State"
          },
          "samples": {
            "default": 0,
            "maximum": 3,
            "minimum": 0,
            "title": "Samples",
            "type": "integer"
          },
          "screenshot": {
            "anyOf": [
              {
                "$ref": "#/$defs/ScreenshotRef"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "session_id": {
            "anyOf": [
              {
                "pattern": "^bo_[a-f0-9]{32}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Session Id"
          }
        },
        "title": "BrowserProvenance",
        "type": "object"
      },
      "ConditionResult": {
        "properties": {
          "baseline_observed": {
            "anyOf": [
              {},
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Baseline Observed"
          },
          "baseline_status": {
            "anyOf": [
              {
                "$ref": "#/$defs/ConditionStatus"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "description": {
            "title": "Description",
            "type": "string"
          },
          "evidence": {
            "$ref": "#/$defs/Evidence"
          },
          "id": {
            "title": "Id",
            "type": "string"
          },
          "latency_ms": {
            "default": 0.0,
            "title": "Latency Ms",
            "type": "number"
          },
          "predicate": {
            "$ref": "#/$defs/Predicate"
          },
          "reason": {
            "title": "Reason",
            "type": "string"
          },
          "required": {
            "title": "Required",
            "type": "boolean"
          },
          "status": {
            "$ref": "#/$defs/ConditionStatus"
          },
          "transition_required": {
            "default": false,
            "title": "Transition Required",
            "type": "boolean"
          }
        },
        "required": [
          "id",
          "description",
          "required",
          "status",
          "predicate",
          "evidence",
          "reason"
        ],
        "title": "ConditionResult",
        "type": "object"
      },
      "ConditionStatus": {
        "enum": [
          "PASS",
          "FAIL",
          "UNKNOWN"
        ],
        "title": "ConditionStatus",
        "type": "string"
      },
      "Evidence": {
        "properties": {
          "fetched_at": {
            "format": "date-time",
            "title": "Fetched At",
            "type": "string"
          },
          "note": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Note"
          },
          "observed": {
            "anyOf": [
              {},
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Observed"
          },
          "provenance": {
            "anyOf": [
              {
                "$ref": "#/$defs/BrowserProvenance"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "provider": {
            "title": "Provider",
            "type": "string"
          },
          "selector": {
            "additionalProperties": true,
            "title": "Selector",
            "type": "object"
          },
          "source_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Source Url"
          }
        },
        "required": [
          "provider",
          "selector"
        ],
        "title": "Evidence",
        "type": "object"
      },
      "Predicate": {
        "properties": {
          "expected": {
            "anyOf": [
              {},
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Expected"
          },
          "op": {
            "enum": [
              "eq",
              "neq",
              "exists",
              "not_exists",
              "contains",
              "contains_all",
              "gte",
              "lte"
            ],
            "title": "Op",
            "type": "string"
          },
          "path": {
            "description": "Dot path into normalized provider state; blank means root.",
            "title": "Path",
            "type": "string"
          }
        },
        "required": [
          "op",
          "path"
        ],
        "title": "Predicate",
        "type": "object"
      },
      "RecoveryInfo": {
        "properties": {
          "attempt": {
            "default": 0,
            "maximum": 20,
            "minimum": 0,
            "title": "Attempt",
            "type": "integer"
          },
          "chain_id": {
            "title": "Chain Id",
            "type": "string"
          },
          "oscillating_conditions": {
            "items": {
              "type": "string"
            },
            "title": "Oscillating Conditions",
            "type": "array"
          },
          "repeated_failures": {
            "items": {
              "type": "string"
            },
            "title": "Repeated Failures",
            "type": "array"
          }
        },
        "required": [
          "chain_id"
        ],
        "title": "RecoveryInfo",
        "type": "object"
      },
      "Remediation": {
        "properties": {
          "action_hint": {
            "title": "Action Hint",
            "type": "string"
          },
          "code": {
            "title": "Code",
            "type": "string"
          },
          "condition": {
            "title": "Condition",
            "type": "string"
          },
          "expected": {
            "default": null,
            "title": "Expected"
          },
          "kind": {
            "const": "doneproof.remediation",
            "default": "doneproof.remediation",
            "title": "Kind",
            "type": "string"
          },
          "observed": {
            "default": null,
            "title": "Observed"
          },
          "retryable": {
            "title": "Retryable",
            "type": "boolean"
          },
          "reverify_after": {
            "enum": [
              "external_action",
              "authoritative_evidence",
              "new_registered_run",
              "contract_revision"
            ],
            "title": "Reverify After",
            "type": "string"
          },
          "status": {
            "enum": [
              "FAIL",
              "UNKNOWN"
            ],
            "title": "Status",
            "type": "string"
          }
        },
        "required": [
          "condition",
          "status",
          "retryable",
          "code",
          "action_hint",
          "reverify_after"
        ],
        "title": "Remediation",
        "type": "object"
      },
      "ScreenshotRef": {
        "additionalProperties": false,
        "properties": {
          "artifact_id": {
            "pattern": "^bs_[a-f0-9]{32}$",
            "title": "Artifact Id",
            "type": "string"
          },
          "bytes": {
            "exclusiveMinimum": 0,
            "maximum": 65536,
            "title": "Bytes",
            "type": "integer"
          },
          "encrypted": {
            "const": true,
            "default": true,
            "title": "Encrypted",
            "type": "boolean"
          },
          "expires_at": {
            "title": "Expires At",
            "type": "integer"
          },
          "media_type": {
            "const": "image/png",
            "default": "image/png",
            "title": "Media Type",
            "type": "string"
          },
          "sha256": {
            "pattern": "^[a-f0-9]{64}$",
            "title": "Sha256",
            "type": "string"
          }
        },
        "required": [
          "artifact_id",
          "sha256",
          "bytes",
          "expires_at"
        ],
        "title": "ScreenshotRef",
        "type": "object"
      },
      "Verdict": {
        "enum": [
          "VERIFIED",
          "PARTIAL",
          "FAILED",
          "UNKNOWN"
        ],
        "title": "Verdict",
        "type": "string"
      },
      "VerificationSummary": {
        "properties": {
          "failed": {
            "title": "Failed",
            "type": "integer"
          },
          "passed": {
            "title": "Passed",
            "type": "integer"
          },
          "providers": {
            "items": {
              "type": "string"
            },
            "title": "Providers",
            "type": "array"
          },
          "required": {
            "title": "Required",
            "type": "integer"
          },
          "total": {
            "title": "Total",
            "type": "integer"
          },
          "unknown": {
            "title": "Unknown",
            "type": "integer"
          }
        },
        "required": [
          "total",
          "required",
          "passed",
          "failed",
          "unknown",
          "providers"
        ],
        "title": "VerificationSummary",
        "type": "object"
      }
    },
    "properties": {
      "assurance_level": {
        "default": "submitted",
        "description": "Whether DoneProof established the assurance boundary before execution.",
        "enum": [
          "registered",
          "submitted"
        ],
        "title": "Assurance Level",
        "type": "string"
      },
      "contract_hash": {
        "default": "",
        "description": "SHA-256 of the exact canonical completion contract.",
        "title": "Contract Hash",
        "type": "string"
      },
      "contract_id": {
        "description": "Completion contract verified by this receipt.",
        "title": "Contract Id",
        "type": "string"
      },
      "duration_ms": {
        "default": 0.0,
        "title": "Duration Ms",
        "type": "number"
      },
      "key_id": {
        "default": "",
        "title": "Key Id",
        "type": "string"
      },
      "previous_receipt_hash": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Previous Receipt Hash"
      },
      "previous_receipt_id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Previous Receipt Id"
      },
      "public_key": {
        "default": "",
        "title": "Public Key",
        "type": "string"
      },
      "receipt_hash": {
        "default": "",
        "title": "Receipt Hash",
        "type": "string"
      },
      "receipt_id": {
        "description": "Unique verification receipt identifier.",
        "title": "Receipt Id",
        "type": "string"
      },
      "recovery": {
        "anyOf": [
          {
            "$ref": "#/$defs/RecoveryInfo"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "remediation": {
        "items": {
          "$ref": "#/$defs/Remediation"
        },
        "title": "Remediation",
        "type": "array"
      },
      "results": {
        "items": {
          "$ref": "#/$defs/ConditionResult"
        },
        "title": "Results",
        "type": "array"
      },
      "schema_version": {
        "default": "1.0",
        "description": "Verification-receipt schema version.",
        "title": "Schema Version",
        "type": "string"
      },
      "signature": {
        "default": "",
        "title": "Signature",
        "type": "string"
      },
      "signature_alg": {
        "default": "Ed25519",
        "title": "Signature Alg",
        "type": "string"
      },
      "summary": {
        "$ref": "#/$defs/VerificationSummary"
      },
      "task": {
        "description": "Human-readable requested outcome copied from the contract.",
        "title": "Task",
        "type": "string"
      },
      "verdict": {
        "$ref": "#/$defs/Verdict"
      },
      "verified_at": {
        "format": "date-time",
        "title": "Verified At",
        "type": "string"
      }
    },
    "required": [
      "contract_id",
      "task",
      "verdict",
      "summary",
      "results"
    ],
    "title": "VerificationReceipt",
    "type": "object"
  },
  "VerifySession": {
    "additionalProperties": false,
    "properties": {
      "callback_id": {
        "anyOf": [
          {
            "pattern": "^[A-Za-z0-9_-]{1,64}$",
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Callback Id"
      },
      "deadline_seconds": {
        "default": 300,
        "maximum": 3600,
        "minimum": 1,
        "title": "Deadline Seconds",
        "type": "integer"
      }
    },
    "title": "VerifySession",
    "type": "object"
  }
};
