"""Generate typed sync forwarding methods; one async implementation owns policy."""
import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PREFIX = '''# Generated by scripts/generate_sync_sdk.py. Do not edit.
from __future__ import annotations

from functools import partial
from typing import Callable

import httpx
from anyio.from_thread import start_blocking_portal
from pydantic import JsonValue

from .assurance_models import AssuranceSession, DurableJob
from .compilation_models import CompilationResult
from .connection_api import ConnectionList, ConnectionView
from .domain import CapabilityResponse
from .sdk_async import AsyncDoneProof
from .sdk_common import Cancellation, ConnectionOnboarding, ProviderCatalog, RequestLog


class _Resource:
    def __init__(self, resource, invoke):
        self._async, self._invoke = resource, invoke


class DoneProof:
    """Synchronous facade using one owned event loop and the async policy implementation.

    Close the client or use a context manager to release its worker thread.
    Custom transports use httpx.AsyncBaseTransport in both client variants.
    """
    def __init__(self, *, api_key: str, base_url: str = 'https://www.getdoneproof.com',
                 timeout: float = 30, transport: httpx.AsyncBaseTransport | None = None,
                 log_hook: Callable[[RequestLog], None] | None = None):
        self._async = AsyncDoneProof(api_key=api_key, base_url=base_url, timeout=timeout,
                                    transport=transport, log_hook=log_hook)
        self._context = start_blocking_portal()
        self._portal = self._context.__enter__()
        self._closed = False
        self.assurance = Assurance(self._async.assurance, self._invoke)
        self.providers = Providers(self._async.providers, self._invoke)

    def _invoke(self, function, *args, **kwargs):
        return self._portal.call(partial(function, *args, **kwargs))

    def close(self):
        if not self._closed:
            try:
                self._invoke(self._async.close)
            finally:
                self._closed = True
                self._context.__exit__(None, None, None)

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()

    verify_receipt = staticmethod(AsyncDoneProof.verify_receipt)
'''


def generate():
    source = ast.parse((ROOT / 'doneproof/sdk_async.py').read_text(encoding='utf-8'))
    result = PREFIX
    for node in source.body:
        if not isinstance(node, ast.ClassDef) or node.name not in {'AsyncDoneProof', 'Assurance', 'Providers'}:
            continue
        if node.name != 'AsyncDoneProof':
            result += '\n\nclass ' + node.name + '(_Resource):\n'
        for method in node.body:
            if not isinstance(method, ast.AsyncFunctionDef) or method.name.startswith('_') or method.name == 'close':
                continue
            args = [ast.Name(id=a.arg, ctx=ast.Load()) for a in method.args.args[1:]]
            keys = [ast.keyword(arg=a.arg, value=ast.Name(id=a.arg, ctx=ast.Load())) for a in method.args.kwonlyargs]
            call = ast.Call(func=ast.Attribute(value=ast.Name(id='self', ctx=ast.Load()), attr='_invoke', ctx=ast.Load()),
                args=[ast.Attribute(value=ast.Attribute(value=ast.Name(id='self', ctx=ast.Load()), attr='_async', ctx=ast.Load()),
                                    attr=method.name, ctx=ast.Load()), *args], keywords=keys)
            forwarding = ast.FunctionDef(name=method.name, args=method.args, body=[ast.Return(call)],
                                          decorator_list=[], returns=method.returns)
            result += '\n' + '\n'.join('    ' + line for line in ast.unparse(ast.fix_missing_locations(forwarding)).splitlines()) + '\n'
    return result


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target, content = ROOT / 'doneproof/sdk_sync.py', generate()
    if args.check:
        if target.read_text(encoding='utf-8') != content:
            raise SystemExit('Synchronous SDK is stale')
    else:
        target.write_text(content, encoding='utf-8', newline='\n')
