"""Generate the provider reference from the same declarations used at runtime."""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from doneproof.provider_registry import default_registry  # noqa: E402


def render(registry):
    lines = ["# Installed provider reference", "",
             "Generated by `python scripts/provider_docs.py`; declarations also appear at authenticated `GET /v1/providers`.", ""]
    for definition in registry:
        spec = definition.manifest
        lines.extend([f"## {spec.display_name} (`{spec.provider_id}` {spec.version})", "", spec.description, "",
                      f"Resources: {', '.join(spec.resource_types)}. Evidence sensitivity: **{spec.evidence_sensitivity}**.", "",
                      "```json", json.dumps(spec.model_dump(mode="json"), indent=2, ensure_ascii=False), "```", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "docs/providers.md")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--installed", action="store_true", default=True, help="Include installed doneproof.providers entry points (default)")
    args = parser.parse_args()
    rendered = render(default_registry(plugins=args.installed))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            parser.exit(1, "Provider documentation differs from the installed registry. Regenerate it.\n")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
