"""Generate TypeScript declarations and runtime schemas from public Python models."""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from doneproof.assurance_models import (  # noqa: E402
    AssuranceSession,
    CompletionEvent,
    DurableJob,
    PrepareSession,
    ReverifySession,
    VerifySession,
)
from doneproof.compilation_models import CompilationResult  # noqa: E402
from doneproof.connection_api import ConnectionList, ConnectionView  # noqa: E402
from doneproof.domain import CapabilityResponse, VerificationReceipt  # noqa: E402
from doneproof.sdk_common import ConnectionOnboarding, ProviderCatalog  # noqa: E402

MODELS = [AssuranceSession, CompletionEvent, DurableJob, PrepareSession, ReverifySession, VerifySession,
          CompilationResult, ConnectionList, ConnectionView, CapabilityResponse, VerificationReceipt,
          ConnectionOnboarding, ProviderCatalog]


def ts(schema):
    if '$ref' in schema:
        return schema['$ref'].rsplit('/', 1)[1]
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(v) for v in schema['enum'])
    for key in ['anyOf', 'oneOf', 'allOf']:
        if key in schema:
            return '(' + (' & ' if key == 'allOf' else ' | ').join(ts(v) for v in schema[key]) + ')'
    kind = schema.get('type')
    if kind == 'object':
        fields = [json.dumps(k) + ('' if k in schema.get('required', []) else '?') + ': ' + ts(v) + ';'
                  for k, v in schema.get('properties', {}).items()]
        additional = schema.get('additionalProperties')
        if isinstance(additional, dict):
            fields.append('[key: string]: ' + ts(additional) + ';')
        if not fields:
            return 'Record<string, unknown>'
        return '{ ' + ' '.join(fields) + ' }'
    if kind == 'array':
        return '(' + ts(schema.get('items', {})) + ')[]'
    return {'string': 'string', 'integer': 'number', 'number': 'number', 'boolean': 'boolean', 'null': 'null'}.get(kind, 'unknown')


def artifacts():
    definitions, schemas = {}, {}
    for model in MODELS:
        schema = model.model_json_schema()
        schemas[model.__name__] = schema
        for name, definition in {**schema.get('$defs', {}), model.__name__: {k: v for k, v in schema.items() if k != '$defs'}}.items():
            if name in definitions and definitions[name] != definition:
                raise ValueError('Conflicting shared schema ' + name)
            definitions[name] = definition
    types = '// Generated by scripts/sdk_schemas.py. Do not edit.\n'
    types += '\n'.join('export type ' + name + ' = ' + ts(value) + ';' for name, value in sorted(definitions.items()))
    types += '\nexport interface ModelMap {\n' + '\n'.join('  ' + model.__name__ + ': ' + model.__name__ + ';' for model in MODELS) + '\n}\n'
    return {'sdk/typescript/src/models.ts': types,
            'sdk/typescript/src/schemas.ts': '// Generated by scripts/sdk_schemas.py. Do not edit.\nexport const schemas = ' + json.dumps(schemas, sort_keys=True, indent=2) + ';\n'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, body in artifacts().items():
        target = ROOT / name
        if args.check:
            if not target.exists() or target.read_text(encoding='utf-8') != body:
                raise SystemExit('SDK schema is stale: ' + name)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding='utf-8', newline='\n')
